version: 3

volumes:
    prometheus_data: {}
    grafana_data: {}
    
services:
  prometheus:
    image: prom/prometheus:v2.20.0
    container_name: prometheus
    volumes: /prometheus:/etc/prometheus

  grafana_data:
    volumes: